import Head from "next/head";
import styles from "../styles/Home.module.css";
import GeneratePDF from "../components/GeneratePDF";

export default function Home({ people }) {
  return (
    <div className={styles.Homecontainer}>
      <div className={styles.container}>
        <Head>
          <title> Generated PDF Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Next.js PDF Generation (Full Stack Focus)​
          </h1>

          <div>
            <div>
              <ul>
                {people.map(({ name, role }, i) => (
                  <li key={i} className={styles.card}>
                    {name}
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <GeneratePDF person={people} />
        </main>
      </div>
      {/* <div>
        <hr></hr>
      </div> */}
      <div className={styles.footer}>
        <p>
          Shubha Bundela <br></br>FullStack Developer​<br></br>​
          <a href="mailto:shubhabundela071@gmail.com">
            shubhabundela071@gmail.com
          </a>
        </p>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/people");
  const people = await res.json();

  return {
    props: {
      people,
    },
  };
}
